Feature/regenerate pdf
lunasoft/sw-sdk-dotnet pull request #100
Opened 2022-12-09 20:24 UTC by marifersw

Se agrega el servicio Regenerar Pdf

2022-12-12 17:26 UTC, SwAeyrton requested changes

2022-12-12 17:26 UTC, SwAeyrton commented on SAT.Services/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.1.1")]
A este proyecto no se lo modifica la version

2022-12-12 17:26 UTC, SwAeyrton commented on SW-sdk-45/Services/RegeneratePdf/RegeneratePdf.cs
> +            RegeneratePdfResponseHandler handler = new RegeneratePdfResponseHandler();
En el constructor ya creas un objeto handler, o bien quitas la creacion en el contructor o eliminas este.

2022-12-12 17:26 UTC, SwAeyrton commented on SW-sdk/Services/RegeneratePdf/RegeneratePdf.cs
> +            RegeneratePdfResponseHandler handler = new RegeneratePdfResponseHandler();
Aplica lo mismo, ya creas un objeto en el constructor de la clase.

2022-12-12 17:26 UTC, SwAeyrton commented on SW-sdk/Services/RegeneratePdf/RegeneratePdf.cs
> +    public class RegeneratePdf : RegeneratePdfService
No es necesario crear una clase RegeneratePdf, el metodo forma parte de API Pdf por lo que la recomendacion es solo agregar un metodo a Pdf Service, tal y como se hizo en la actualizacion de Java 1.6 https://github.com/lunasoft/sw-sdk-java/blob/develop/src/main/java/Services/Pdf/SWPdfService.java

2022-12-14 02:38 UTC, SwAeyrton requested changes

2022-12-14 02:38 UTC, SwAeyrton commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse RegenerarPdf(Guid uuid) {
Aqui te falta la documentacion del metodo, puedes basarte en otros metodos que lo tenga u otras librerias, igual aqui esta la documentacion https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/

2022-12-14 02:38 UTC, SwAeyrton commented on Test_SW-sdk-45/Services/Pdf/Pdf_Test.cs
> +            Assert.IsTrue(response.message == "Solicitud se proceso correctamente.");
Aqui hay un problema, este endpoint no regresar status ni nada, solo regresa un message pero nosotros en la libreria debemos agregar esto faltante 
![image](https://user-images.githubusercontent.com/88451104/207491548-2d3d1801-9c85-445a-88ab-51521cbb3351.png)
Un tip seria mi ultimo PR en la libreria de NetStandard.

2022-12-14 20:26 UTC, FerCarrilloM approved these changes

2022-12-15 18:27 UTC, SwAeyrton approved these changes

2022-12-15 19:38 UTC, merged