Fix sat services master
lunasoft/sw-sdk-dotnet pull request #117
Opened 2023-06-09 22:05 UTC by martinfnsw

Fix sat services master

2023-06-09 22:11 UTC, FerCarrilloM approved these changes

2023-06-09 22:22 UTC, SwAeyrton requested changes, later dismissed
no se ve otra modificacion mas que la version

2023-06-12 15:07 UTC, marifersw approved these changes

2023-06-12 15:13 UTC, SebastianSW approved these changes

2023-06-12 17:11 UTC, ReyesSW approved these changes

2023-06-12 17:13 UTC, merged