Hotfix/ss 330
lunasoft/sw-sdk-dotnet pull request #123
Opened 2023-08-18 19:59 UTC by FerCarrilloM

2023-08-18 20:12 UTC, SebastianSW approved these changes

2023-08-21 15:14 UTC, ReyesSW approved these changes

2023-08-21 15:15 UTC, marifersw approved these changes

2023-08-21 15:26 UTC, SwAeyrton requested changes

2023-08-21 15:26 UTC, SwAeyrton commented on SW-sdk-45/Properties/AssemblyInfo.cs
> -[assembly: AssemblyFileVersion("0.0.19.7")]
la version sube a .8, no .10

2023-08-21 15:35 UTC, SwAeyrton approved these changes

2023-08-21 15:37 UTC, merged