Feature/update files
lunasoft/sw-sdk-dotnet pull request #124
Opened 2023-08-21 19:57 UTC by marifersw

2023-08-21 20:06 UTC, ReyesSW approved these changes

2023-08-21 21:56 UTC, FerCarrilloM approved these changes

2023-08-22 00:09 UTC, SebastianSW approved these changes

2023-08-22 19:16 UTC, SwAeyrton requested changes
Lo ideal para los nombres de los resources, es usar nombres cortos, no es necesario mantener el nombre original de los certirficados.
Las UT fallan, los resources no estan agregados correctamente.

2023-08-23 19:33 UTC, SwAeyrton requested changes

2023-08-23 19:33 UTC, SwAeyrton commented on Test_SW-sdk-45/UT_Service_Validation.cs
>          public void UT_Service_Validation_45_STAMPV4_CCE11()
skipear esta UT, al ser CCE, el valor de tipo cambio usd cambia diariamente, por lo que no se hace mantenible

2023-08-23 20:02 UTC, martinfnsw requested changes

2023-08-23 20:02 UTC, martinfnsw commented on SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.19.11")]
Al ser un feature se actualiza el tercer dígito

2023-08-23 22:47 UTC, martinfnsw approved these changes

2023-08-23 22:48 UTC, SwAeyrton approved these changes

2023-08-23 22:52 UTC, merged