Update AccountBalance
lunasoft/sw-sdk-dotnet pull request #125
Opened 2023-08-25 18:10 UTC by martinfnsw

Se actualizan clases para AccountBalance

2023-08-28 16:45 UTC, marifersw approved these changes

2023-08-28 16:46 UTC, FerCarrilloM approved these changes

2023-08-28 16:55 UTC, SwAeyrton requested changes

2023-08-28 16:55 UTC, SwAeyrton commented on SW-sdk-45/Services/Account/AccountBalance/Account.cs
> +        public BalanceAccount(string url, string user, string password, int proxyPort = 0, string proxy = null) : base(url, user, password, proxy, proxyPort)
No entiendo por que hay 3 sobercargas

2023-08-28 16:55 UTC, SwAeyrton commented on SW-sdk-45/Services/Account/AccountBalance/Account.cs
> +    public class BalanceAccount : BalanceAccountService
Considero que deberia mantenerse un solo nombramiento para la clase, es decir, si el archivo y el namespace se llaman AccountBalance, la clase tambien deberia llamarse asi.

2023-08-29 05:04 UTC, martinfnsw commented on SW-sdk-45/Services/Account/AccountBalance/Account.cs
> +        public BalanceAccount(string url, string user, string password, int proxyPort = 0, string proxy = null) : base(url, user, password, proxy, proxyPort)
dejé las 2 sobrecargas y se actualizó el método que ya estaba al nuevo endpoint

2023-08-29 05:05 UTC, martinfnsw commented on SW-sdk-45/Services/Account/AccountBalance/Account.cs
> +    public class BalanceAccount : BalanceAccountService
Me parece bien, se actualizó el nombre de las clases en ambos proyectos

2023-08-29 15:47 UTC, ReyesSW approved these changes

2023-08-29 15:52 UTC, SebastianSW approved these changes

2023-08-30 16:33 UTC, SwAeyrton requested changes

2023-08-30 16:33 UTC, SwAeyrton commented on SW-sdk-45/Services/ResponseHandler.cs
> +        public virtual T GetResponse(string url, Dictionary<string, string> headers, string path, HttpContent content, HttpClientHandler proxy)
ya existe un metodo para realizar el http post con los mismos parametros, por que crear uno nuevo?

2023-08-30 16:33 UTC, SwAeyrton commented on SW-sdk-45/Services/Account/AccountBalance/AccountResponseHandler.cs
> +namespace SW.Services.Account.AccountBalance
hay que mantener los mismo nombres que se coloquen en el nombre de la clase, el archivo se llama AccountResponseHandler pero la clase se llama BalanceAccountResponseHandler

2023-08-30 16:33 UTC, SwAeyrton commented on SW-sdk-45/Services/Account/AccountBalance/AccountService.cs
>      public abstract class BalanceAccountService : Services
lo mismo, el archivo se llama Accountservice pero la clae se llama BalanceAccountService

2023-08-31 00:04 UTC, SwAeyrton approved these changes

2023-08-31 00:24 UTC, merged