Se genera metodo para consumir el path de analytics.
lunasoft/sw-sdk-dotnet pull request #136
Opened 2023-11-15 03:29 UTC by ReyesSW

Se genera el método para consumir Analytics justo como el cliente lo requiere, para el método de issue

2023-11-15 20:02 UTC, SebastianSW approved these changes

2023-11-16 15:30 UTC, FerCarrilloM approved these changes

2023-11-16 16:49 UTC, mendozagit commented
Hola chicos, por curiosidad que ofrece el feature "analytics"?

2023-11-16 17:18 UTC, ReyesSW commented
> Hola chicos, por curiosidad que ofrece el feature "analytics"?
Buen día.
El feature "analytics" es una funcionalidad temporal con costo, diseñada para monitorear y rastrear de cerca las interacciones con el web service, especialmente útil para analizar el comportamiento de solicitudes en paths específicos. Por lo tanto para su uso se debe de activar en nuestros servicios y previa revision por parte del area comercial.

2023-11-16 18:07 UTC, mendozagit commented
@ReyesSW, gracias por la orientacion.

2023-11-16 18:26 UTC, marifersw approved these changes

2023-11-16 22:36 UTC, SwAeyrton requested changes

2023-11-16 22:36 UTC, SwAeyrton commented on SW-sdk-45/Services/Issue/IssueAnalytics.cs
> +    public class IssueAnalytics : BaseStampV4
Esta clase es innecesaria, se puede realizar el llamado al metodo nuevo manteniendo la misma forma de crear una instancia de StampV4.

2023-11-16 22:36 UTC, SwAeyrton commented on SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.24.3")]
Hay que subir la version tambien de la otra libreria aunque no se haya trabajado nada en ella, esto para mantener un versionado uniforme y evitar discrepancias posteriores

2023-11-16 22:36 UTC, SwAeyrton commented on Test_SW-sdk-45/Services/Issue/Issue_Test.cs
> +}
?

2023-11-16 22:36 UTC, SwAeyrton commented on Test_SW-sdk-45/Services/Issue/IssueV2_Test.cs
> +        public void Stamp_Test_45_StampV4_V4_customId_Analytics()
Falta UT de error

2023-11-17 14:38 UTC, martinfnsw approved these changes

2023-11-17 17:41 UTC, ReyesSW commented on Test_SW-sdk-45/Services/Issue/IssueV2_Test.cs
> +        public void Stamp_Test_45_StampV4_V4_customId_Analytics()
Se agrega UT de error

2023-11-17 17:41 UTC, ReyesSW commented on Test_SW-sdk-45/Services/Issue/Issue_Test.cs
> +}
Se corrije este cambio

2023-11-17 17:42 UTC, ReyesSW commented on SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.24.3")]
Se sube la version

2023-11-17 17:42 UTC, ReyesSW commented on SW-sdk-45/Services/Issue/IssueAnalytics.cs
> +    public class IssueAnalytics : BaseStampV4
Al no existir el V4 para issue se genera está para poder tomar como base el basev4

2023-11-17 18:46 UTC, SwAeyrton approved these changes

2023-11-17 18:59 UTC, merged