Métodos para timbrado masivo.
lunasoft/sw-sdk-dotnet pull request #37
Opened 2019-01-30 23:18 UTC by JuanGamezSW

Se añaden métodos para timbrado concurrente sin duplicar facturas por medio de varios hilos de ejecución.

2019-01-30 23:41 UTC, alxcodes approved these changes
Solo subule la version al assembly

2019-01-31 16:19 UTC, hermesjimenez requested changes

2019-01-31 16:19 UTC, hermesjimenez commented on SW-sdk-45/Services/Stamp/BaseStamp.cs
> +        public virtual ConcurrentBag<StampResponseV3> TimbrarV3(string[] xmls, bool isb64 = false)
Creo que nos faltaria saber a que xml corresponde el error que regresa en la lista. Normalmente en las respuestas no regresamos la referencia del xml que se mando timbrar , solo se regresa el error. Si envio 2 xml y los 2 tienen error , como sabria cual error corresponde a cual ?

2019-01-31 19:59 UTC, JuanGamezSW commented on SW-sdk-45/Services/Stamp/BaseStamp.cs
> +        public virtual ConcurrentBag<StampResponseV3> TimbrarV3(string[] xmls, bool isb64 = false)
Añadido.

2019-02-07 17:25 UTC, hermesjimenez approved these changes

2019-02-07 17:26 UTC, merged