Se Agrega Metodo Timbrado V4 Stamp
lunasoft/sw-sdk-dotnet pull request #50
Opened 2021-01-13 23:11 UTC by RICH-CD

Se agrega Timbrado V4 Stamp

2021-01-13 23:23 UTC, JuanGamezSW requested changes

2021-01-13 23:23 UTC, JuanGamezSW commented on Test_SW-sdk-45/Services/Stamp/Stamp_Test.cs
> +        [TestMethod]
Agregar UT sin email.

2021-01-13 23:23 UTC, JuanGamezSW commented on Test_SW-sdk-45/Services/Stamp/Stamp_Test.cs
> +        }
UT con varios email.

2021-01-13 23:23 UTC, JuanGamezSW commented on SW-sdk/Services/Stamp/StampServiceV4.cs
> +        internal virtual HttpWebRequest RequestStamping(byte[] xml, string version, string format, string operation, string email)
hace falta customId

2021-01-13 23:23 UTC, JuanGamezSW commented on SW-sdk/Services/Stamp/StampServiceV4.cs
> +            request.Headers.Add("email", email);
Me parece que si fuera null email no se tendría que agregar.

2021-01-13 23:23 UTC, JuanGamezSW commented on SW-sdk/Services/Stamp/BaseStampV4.cs
> +        public virtual StampResponseV4 TimbrarV4(string xml, string email = null, bool isb64 = false)
falta parametro "customId" opcional.

2021-01-13 23:23 UTC, JuanGamezSW commented on SW-sdk-45/Services/Stamp/StampServiceV4.cs
> +                    { "email", email }
si es null no se tendría que agregar.
Faltaría tambien el customId.

2021-01-14 20:30 UTC, alxcodes commented
revisar estas UT para que te orientes con las que te pueden faltar
https://github.com/lunasoft/SW-sdk-NetStandard/blob/master/test/sdk-test/Services/Stamp/StampV4_Test.cs

2021-01-18 19:22 UTC, RICH-CD commented on Test_SW-sdk-45/Services/Stamp/Stamp_Test.cs
> +        [TestMethod]
Se agrega clase StampV4_Test para meter mas TestMethod (UT sin email, UT con customid, UT con email y customid, UT con varios correos)

2021-01-18 19:22 UTC, RICH-CD commented on Test_SW-sdk-45/Services/Stamp/Stamp_Test.cs
> +        }
Se agrega clase StampV4_Test para meter mas TestMethod (UT sin email, UT con customid, UT con email y customid, UT con varios correos)

2021-01-18 19:22 UTC, RICH-CD commented on SW-sdk/Services/Stamp/StampServiceV4.cs
> +        internal virtual HttpWebRequest RequestStamping(byte[] xml, string version, string format, string operation, string email)
Se Agrega customid

2021-01-18 19:23 UTC, RICH-CD commented on SW-sdk/Services/Stamp/StampServiceV4.cs
> +            request.Headers.Add("email", email);
Se valida que email sea distinto de null para agregarlo al request

2021-01-18 19:23 UTC, RICH-CD commented on SW-sdk/Services/Stamp/BaseStampV4.cs
> +        public virtual StampResponseV4 TimbrarV4(string xml, string email = null, bool isb64 = false)
Se agrega customid

2021-01-18 19:23 UTC, RICH-CD commented on SW-sdk-45/Services/Stamp/StampServiceV4.cs
> +                    { "email", email }
Se agregan validaciones y customid

2021-01-18 22:06 UTC, JuanGamezSW approved these changes

2021-01-19 00:05 UTC, lupitalvarado approved these changes

2021-01-19 00:25 UTC, helttonrl approved these changes

2021-01-19 00:33 UTC, merged