Feature/stampv4_responsev4
lunasoft/sw-sdk-dotnet pull request #65
Opened 2022-03-17 23:26 UTC by SwAeyrton

2022-03-17 23:31 UTC, martinfnsw approved these changes

2022-03-17 23:39 UTC, helttonrl requested changes
Deje un comentario en ut que creo deben ir.

2022-03-17 23:39 UTC, helttonrl commented on Test_SW-sdk-45/Services/Stamp/StampV4XML_test.cs
> +        public void Stamp_Test_StampV4XMLV4_DifCustomID_byToken()
En estas UT creo que deben ir los assert que vengan valores en todos los campos que debe regresar el timbrado V4 (codigoqr, cadenaoriginal etc)
![image](https://user-images.githubusercontent.com/23102756/158910992-972e4ef8-f367-4195-8c4f-d72d3d708f4b.png)

2022-03-18 00:54 UTC, helttonrl approved these changes

2022-03-18 02:31 UTC, merged