Add GeneratePdf
lunasoft/sw-sdk-dotnet pull request #87
Opened 2022-09-27 04:44 UTC by martinfnsw

- Se actualiza método para generar pdf
- Se agregan pruebas unitarias
- Se actualiza usuario para test

2022-09-27 14:01 UTC, marifersw approved these changes

2022-09-27 14:16 UTC, ReyesSW approved these changes

2022-09-27 14:22 UTC, FerCarrilloM approved these changes

2022-09-27 14:44 UTC, SwAeyrton requested changes

2022-09-27 14:44 UTC, SwAeyrton commented on Test_SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.1")]
A los test no se requiere subir la version.

2022-09-27 14:44 UTC, SwAeyrton commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdf(string xml, string logo, string templateId, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Considero que un enum con las plantillas sería un plus.

2022-09-27 14:44 UTC, SwAeyrton commented on SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.14.8")]
Falta subir la version.

2022-09-27 16:31 UTC, martinfnsw commented on SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.14.8")]
volví a jalar los cambios de dev con la versión correcta

2022-09-27 16:32 UTC, martinfnsw commented on Test_SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.1")]
Muy bien, se baja la versión

2022-09-27 21:12 UTC, SwAeyrton requested changes

2022-09-27 21:12 UTC, SwAeyrton commented on Test_SW-sdk/Test_SW-sdk.csproj
> +      <HintPath>..\..\..\..\..\Downloads\sw-sdk-dotnet-master\sw-sdk-dotnet-master\Test_SW-sdk\bin\Debug\SW.Tools.dll</HintPath>
Me dio un error de compilacion porque esta referencia está agregada como local

2022-09-28 18:47 UTC, martinfnsw commented on Test_SW-sdk/Test_SW-sdk.csproj
> +      <HintPath>..\..\..\..\..\Downloads\sw-sdk-dotnet-master\sw-sdk-dotnet-master\Test_SW-sdk\bin\Debug\SW.Tools.dll</HintPath>
Agregué la referencia desde nuget

2022-09-28 18:49 UTC, martinfnsw commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdf(string xml, string logo, string templateId, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Agregué los enum con los métodos para cada templateid (solo cfdi 4.0). Me gusta como se ve con ese plus

2022-09-28 19:03 UTC, SwAeyrton requested changes

2022-09-28 19:03 UTC, SwAeyrton commented on SW-sdk/Helpers/TemplatesId.cs
> +    internal enum TemplatesId
Faltan los templates de CFDI 3.3

2022-09-28 19:03 UTC, SwAeyrton commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdfCfdi40(string xml, string logo, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Considero que esto no esta bien, el metodo estaba bien como estaba, solo es modificar que el parametro template sea un enum y no un string

2022-09-28 22:36 UTC, martinfnsw commented on SW-sdk/Helpers/TemplatesId.cs
> +    internal enum TemplatesId
Se agregan los templates faltantes

2022-09-28 22:41 UTC, martinfnsw commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdfCfdi40(string xml, string logo, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Actualicé la clase y los métodos con los enum públicos. 
intenté cambiar los valores de los enum para no confundir a los clientes con los nombres, ¿conoces alguna manera? se me ocurre generar un método interno en la clase TemplatesId o simplemente indicar los valores de los template en el README

2022-09-28 22:44 UTC, SwAeyrton commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdfCfdi40(string xml, string logo, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
No entiendo bien a que te refieres pero la forma en la que lo estoy trabajando en la de NetStandard es asi 
![image](https://user-images.githubusercontent.com/88451104/192901666-5c5b3426-ec6b-4802-87ff-6f3391d1c6b2.png)

2022-09-30 22:25 UTC, martinfnsw commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdfCfdi40(string xml, string logo, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Los actualicé de la misma manera

2022-09-30 22:43 UTC, SwAeyrton requested changes

2022-09-30 22:43 UTC, SwAeyrton commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
>      public class PdfUnit
Fallan las UT

2022-09-30 22:43 UTC, SwAeyrton commented on SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.15.1")]
Se debe subir la version tambien en el otro proyecto.

2022-09-30 22:43 UTC, SwAeyrton commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdf(string xml, string logo,TemplatesId templateId, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Falta una sobrecarga de este metodo donde se pueda recibir como parametro un custom template.

2022-09-30 22:43 UTC, SwAeyrton commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
>      public class PdfUnit
![image](https://user-images.githubusercontent.com/88451104/193365999-589d8afa-571b-45b7-be1e-80bd629e30cb.png)

2022-10-03 14:17 UTC, martinfnsw commented on SW-sdk/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.15.1")]
El método para sdk-45 lo está trabajando Reyes

2022-10-03 14:17 UTC, martinfnsw commented on SW-sdk/Services/Pdf/BasePdf.cs
> +        public virtual PdfResponse GenerarPdf(string xml, string logo,TemplatesId templateId, Dictionary<string, string> ObservacionesAdicionales = null, bool isB64 = false)
Agregué la sobrecarga faltante

2022-10-03 14:17 UTC, martinfnsw commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
>      public class PdfUnit
Se corrigen las UT

2022-10-03 15:33 UTC, SwAeyrton requested changes

2022-10-03 15:33 UTC, SwAeyrton commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
> +        public void UT_GeneratePdf()
Me sigue marcando error, segun esto es porque tienes agregado un archivo en local fileXml.xml
![image](https://user-images.githubusercontent.com/88451104/193617237-ac84835f-0566-4b0e-ae40-648bc6a51c78.png)

2022-10-03 15:33 UTC, SwAeyrton commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
>      public class PdfUnit
Hacen falta UT para la sobrecarga de el template por string, y tambien cuando isB674 es true.

2022-10-04 23:27 UTC, martinfnsw commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
> +        public void UT_GeneratePdf()
Se agregan los archivos al proyecto

2022-10-04 23:27 UTC, martinfnsw commented on Test_SW-sdk/Services/Pdf/Pdf_Test.cs
>      public class PdfUnit
Se agregan UT faltantes

2022-10-05 00:43 UTC, SwAeyrton approved these changes

2022-10-05 18:05 UTC, merged