Se realiza update para la API PDF.
lunasoft/sw-sdk-dotnet pull request #89
Opened 2022-10-10 17:36 UTC by ReyesSW

Se realiza update para la API PDF.
Metodo que genera y obtiene el pdf en base64 de un documento XMl y a una plantilla.
Se agregan funciones para complementar funcionalidad de la misma API.
Se añaden Testcases para las UnitTest.

2022-10-10 21:36 UTC, SwAeyrton commented on Test_SW-sdk-45/Test_SW-sdk-45.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Eso tu lo agregaste manualmente ?

2022-10-10 21:40 UTC, ReyesSW commented on Test_SW-sdk-45/Test_SW-sdk-45.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
No, que raro, creo que fue el vstudio , al pasar la carpeta y el pdf_test y darle copiar siempre.

2022-10-10 22:26 UTC, martinfnsw approved these changes

2022-10-13 14:45 UTC, SwAeyrton requested changes
Falta subir la version

2022-10-13 14:45 UTC, SwAeyrton commented on SW-sdk-45/SW-sdk-45.csproj
> +    </Compile>
Quitaselo desde properties, ya estan incluidos en el proyecto, esto aplica para los Resources nada mas.

2022-10-13 14:45 UTC, SwAeyrton commented on SW-sdk-45/SW-sdk-45.csproj
> +    </Compile>
![image](https://user-images.githubusercontent.com/88451104/195628344-a7c026d8-dbcf-4205-8fa0-b3b3ef124d9b.png)

2022-10-14 15:06 UTC, SwAeyrton requested changes
Como las dos librerias estan en una misma solucion, se le actualiza la version a ambas, solo eso faltaria

2022-10-14 16:32 UTC, SwAeyrton approved these changes

2022-10-14 16:35 UTC, FerCarrilloM approved these changes

2022-10-14 16:37 UTC, marifersw approved these changes

2022-10-14 17:48 UTC, merged