Feacture/resend email
lunasoft/sw-sdk-dotnet pull request #94
Opened 2022-11-24 16:42 UTC by FerCarrilloM

2022-11-24 16:50 UTC, marifersw approved these changes

2022-11-24 18:20 UTC, ReyesSW approved these changes

2022-11-25 16:20 UTC, martinfnsw reviewed
Lo veo bien, falta actualizar la versión.

2022-11-25 16:41 UTC, SwAeyrton requested changes

2022-11-25 16:41 UTC, SwAeyrton commented on SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.17.2")]
Se resetea el ultimo digito.

2022-11-25 16:41 UTC, SwAeyrton commented on Test_SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
La version de los proyectos de test no se sube,

2022-11-25 16:41 UTC, SwAeyrton commented on SW-sdk/Services/Resend/Resend.cs
> +        public Resend(string url, string urlApi, string user, string password, int proxyPort = 0, string proxy = null) : base(url, urlApi, user, password, proxy, proxyPort)
Se acordó que se debe pasar primero la url del servicio y despues la url necesaria para la autenticacion.

2022-11-25 16:44 UTC, FerCarrilloM commented on Test_SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
Eso fue un error de dedo mientras buscaba la versión, corregí y lo retorne al valor que tenía.

2022-11-25 16:45 UTC, FerCarrilloM commented on SW-sdk-45/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.0.17.2")]
Va, entiendo, muchas gracias.

2022-11-26 00:24 UTC, SwAeyrton requested changes
Con la finalidad de acostumbrarnos a las buenas practicas, te sugiero corregir el nombre de la rama.

2022-11-26 00:24 UTC, SwAeyrton commented on Test_SW-sdk-45/Services/Resend/Resend_Test.cs
> +namespace Resend_Test.Services.Resend_Tests
Seguir el mismo formato que otras UT para la declaracion del namespace.

2022-11-26 00:24 UTC, SwAeyrton commented on Test_SW-sdk-45/Services/Resend/Resend_Test.cs
> +            Assert.IsTrue(resendResult.status == "success");
Faltan asserts verificando la respuesta completa.

2022-11-28 18:38 UTC, SwAeyrton approved these changes

2022-11-28 18:53 UTC, merged